version: '3'
services:
  student_rpc:
    container_name: student_rpc
    build: python/
    restart: always
    networks:
      - microservice
      - default
    
networks:
  default:
    external:
      name: student_network
  microservice:
    external:
      name: microservice_network
  webproxy:
    external:
      name: webproxy
    
