version: "3"
services:
  app:
    container_name: golang_gateway
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./:/app
    command: air ./app/main.go -b 0.0.0.0
    networks:
      - golang-network

  nginx:
    container_name: "nginx_reverproxy"
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - golang-network

networks:
  golang-network:
    external:
      name: golang-network
